Bump dependencies
anyhow: 1.0.95 -> 1.0.99
log: 0.4.22 -> 0.4.27
rand: 0.8.5 -> 0.9.1
thiserror: 2.0.10 -> 2.0.12

The API changed in the rand crate, and the code has been adapted.

Note that crc32c will likely be replaced, so it's not upgraded.